module.exports = [
  {"id":3,"product_id":2,"rating":4,"date":1609325851021,"summary":"I am liking these glasses","body":"They are very dark.  But that's good because I'm in very sunny spots","recommend":"true","reported":"false","reviewer_name":"bigbrotherbenjamin","reviewer_email":"first.last@gmail.com","response":"Glad you're enjoying the product!","helpfulness":5,"photos":[]},
  {"id":2,"product_id":1,"rating":4,"date":1610178433963,"summary":"This product was ok!","body":"I really did not like this product solely because I am tiny and do not fit into it.","recommend":"false","reported":"false","reviewer_name":"mymainstreammother","reviewer_email":"first.last@gmail.com","response":"null","helpfulness":2,"photos":[]},
  {"id":10,"product_id":4,"rating":2,"date":1592977554987,"summary":"These pants are ok!","body":"A little tight on the waist.","recommend":"false","reported":"false","reviewer_name":"bigbrother","reviewer_email":"first.last@gmail.com","response":"null","helpfulness":2,"photos":[{"id":7,"review_id":10,"url":"https://images.unsplash.com/photo-1549812474-c3cbd9a42eb9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=668&q=80"},{"id":9,"review_id":10,"url":"https://images.unsplash.com/photo-1559709319-3ae960cda614?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=668&q=80"},{"id":8,"review_id":10,"url":"https://images.unsplash.com/photo-1560829675-11dec1d78930?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1652&q=80"}]},
  {"id":11,"product_id":5,"rating":4,"date":1612509984089,"summary":"Great shoes!","body":"Now I can get to stomping!","recommend":"true","reported":"false","reviewer_name":"chingy","reviewer_email":"first.last@gmail.com","response":"null","helpfulness":12,"photos":[]},
  {"id":12,"product_id":5,"rating":3,"date":1594890076276,"summary":"They're heavy but great","body":"I like them but they run wide.","recommend":"true","reported":"false","reviewer_name":"thinfootjim","reviewer_email":"first.last@gmail.com","response":"null","helpfulness":3,"photos":[]},
  {"id":13,"product_id":7,"rating":5,"date":1602721790544,"summary":"Ye is good at everything","body":"I mortgaged my house to pay for these","recommend":"true","reported":"false","reviewer_name":"yecrazy","reviewer_email":"first.last@gmail.com","response":"null","helpfulness":2,"photos":[]},
  {"id":14,"product_id":7,"rating":1,"date":1619382006414,"summary":"I don't like Kanye","body":"I didn't buy the shoes but I don't like the man behind them","recommend":"false","reported":"true","reviewer_name":"taylor","reviewer_email":"first.last@gmail.com","response":"null","helpfulness":0,"photos":[]},
  {"id":1,"product_id":1,"rating":5,"date":1596080481467,"summary":"This product was great!","body":"I really did or did not like this product based on whether it was sustainably sourced.  Then I found out that its made from nothing at all.","recommend":"true","reported":"false","reviewer_name":"funtime","reviewer_email":"first.last@gmail.com","response":"null","helpfulness":8,"photos":[]},
  {"id":4,"product_id":2,"rating":4,"date":1593628485253,"summary":"They look good on me","body":"I so stylish and just my aesthetic.","recommend":"true","reported":"false","reviewer_name":"fashionperson","reviewer_email":"first.last@gmail.com","response":"null","helpfulness":1,"photos":[]},
  {"id":8,"product_id":4,"rating":4,"date":1599505939632,"summary":"These pants are fine","body":"I do like these pants","recommend":"true","reported":"false","reviewer_name":"shopaddict","reviewer_email":"first.last@gmail.com","response":"null","helpfulness":2,"photos":[]}
]
